# Acknowledgements {.unnumbered}

I would first like to extend my sincere thanks to Professor Vuong Van Yen and Professor Arthur Charpentier for their academic mentorship. Without their encouragement, I would not have pursued such a challenging and meaningful topic in the insurance field. And without their belief in my abilities, I would not have chosen to pursue an academia career in the first place. 

I am equally grateful to my enterprise tutor, Antoine Paulet as well as my team at Lya Protect, who have provided me with the opportunity and cultivated the best possible environment for me to complete this research at Lya Protect. With my first French-speaking experience, I have learned a lot about the French culture and the insurance industry in France. I am grateful for their support and guidance throughout this journey. I also wish to thank my academic advisor, Maud Thomas, for her guidance and support throughout this research.

I also wish to acknowledge the CAS Trust Scholarship for providing a scholarship for my studies and encouraging me to make meaningful contributions to the field of Actuarial Science.

Finally, my deepest appreciation goes to my greatest supporters: my family and friends. Thank you for being there for me throughout this entire journey and until the next one.